[build]
# This assumes that the Zola site is in a docs folder. If it isn't, you don't need
# to have a `base` variable but you do need the `publish` and `command` variables.
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "v0.17.1"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[plugins]]
	package = "@netlify/plugin-lighthouse"

	[plugins.inputs]
    	output_path = "reports/lighthouse.html"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]

	# to audit a sub path of the build directory
	# route1 audit will use the top level thresholds
	[[plugins.inputs.audits]]
		path = "/"
	[[plugins.inputs.audits]]
		path = "/2022/schedule"
	[plugins.inputs.audits.thresholds]
		performance = 1
		best-practices = 0.92
		seo = 0.98

	[[plugins.inputs.audits]]
		path = "/2022/covid-policy"
	[plugins.inputs.audits.thresholds]
		performance = 1
		best-practices = 0.92
		seo = 0.94